-- Add workflow statuses to PipelineStatus enum (Supabase/Postgres)
-- Safe to run even if rows exist.

ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'NEW_REQUEST';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'DESIGN_ASSIGNED';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'IN_DESIGN';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'DESIGN_DONE';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'PRODUCTION_READY';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'IN_PRODUCTION';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'PRODUCTION_DONE';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE "PipelineStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';