import { useEffect, useState } from "react";
import Pagination from "../../../components/common/Pagination";
import { useDialog } from "../../../components/common/DialogProvider";
import { formatJobId } from "../../../utils/jobFormatting";
import { listOperatorJobsByStatus, operatorWorkflow } from "../../api/operator.api";
import JobDetailActionPanel from "../../../components/common/JobDetailActionPanel";

function cn(...xs) { return xs.filter(Boolean).join(" "); }

export default function OperatorInProduction() {
  const dialog = useDialog();
  const [jobs, setJobs] = useState([]); const [selected, setSelected] = useState(null); const [err, setErr] = useState(""); const [page, setPage] = useState(1); const pageSize = 10;
  async function load() { try { setErr(""); const a = await listOperatorJobsByStatus("IN_PRODUCTION"); const all = (a || []).sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt)); setJobs(all); if (selected) setSelected(all.find((x)=>x.id===selected.id)||null); } catch (e) { setErr(e?.response?.data?.message || "Failed to load production jobs"); } }
  useEffect(() => { load(); }, []);
  async function complete(jobId) { try { await operatorWorkflow(jobId, "OPERATOR_COMPLETE"); dialog.toast("Production completed", "success"); load(); } catch (e) { dialog.toast(e?.response?.data?.message || "Failed", "error"); } }
  const totalPages = Math.max(1, Math.ceil(jobs.length / pageSize)); const pageSafe = Math.min(page, totalPages); const slice = jobs.slice((pageSafe - 1) * pageSize, pageSafe * pageSize);
  return <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><div className="bg-white border border-zinc-200 rounded-2xl p-6 shadow-sm transition-all duration-300 hover:shadow-md hover:border-primary/20"><div className="flex items-center justify-between"><h2 className="text-2xl font-extrabold text-primary">In Production</h2><button onClick={load} className="px-3 py-2 rounded-xl bg-bgLight text-primary font-bold transition-all duration-300 hover:-translate-y-0.5 hover:shadow-sm">Refresh</button></div>{err && <div className="mt-3 text-red-600 font-bold">{err}</div>}<div className="mt-4 overflow-auto rounded-2xl border border-zinc-200"><table className="min-w-full text-sm"><thead className="text-left text-zinc-500 bg-bgLight"><tr><th className="py-2 px-3">Job#</th><th className="py-2 px-3">Customer</th><th className="py-2 px-3">Work</th><th className="py-2 px-3">Status</th><th className="py-2 px-3">Action</th></tr></thead><tbody>{slice.map((j)=><tr key={j.id} onClick={() => setSelected(j)} className={cn("border-t border-zinc-200 cursor-pointer hover:bg-zinc-50 transition-colors", selected?.id===j.id ? "bg-bgLight":"")}><td className="py-2 px-3 font-extrabold text-primary">{formatJobId(j.jobNo)}</td><td className="py-2 px-3">{j.customerName}</td><td className="py-2 px-3">{j.workType}</td><td className="py-2 px-3 font-bold">{j.status}</td><td className="py-2 px-3"><button onClick={(e)=>{e.stopPropagation();complete(j.id);}} className="px-3 py-2 rounded-xl bg-success text-white font-semibold transition-all duration-300 hover:-translate-y-0.5 hover:shadow-sm">Production Completed</button></td></tr>)}{slice.length===0&&<tr><td colSpan={5} className="py-4 px-3 text-zinc-500">No active production jobs.</td></tr>}</tbody></table></div><Pagination page={pageSafe} totalPages={totalPages} onChange={setPage} /></div><JobDetailActionPanel selected={selected}>{selected ? <button onClick={() => complete(selected.id)} className="w-full px-4 py-3 rounded-xl bg-success text-white font-semibold transition-all duration-300 hover:-translate-y-0.5 hover:shadow-sm">Production Completed</button> : null}</JobDetailActionPanel></div>;
}
